-- 코드를 입력하세요
SELECT TITLE, g.BOARD_ID,r.REPLY_ID ,r.WRITER_ID,r.CONTENTS,DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD g INNER JOIN USED_GOODS_REPLY r ON g.BOARD_ID=r.BOARD_ID
WHERE g.CREATED_DATE LIKE '2022-10%'
ORDER BY r.CREATED_DATE ASC, TITLE ASC;